In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score


In [3]:
X=pd.read_csv('X_final.csv')
y=pd.read_csv('y.csv')
X

online_order  book_table  votes  approx_cost(for two people)  \
0                 1           1    775                          800   
1                 1           0    787                          800   
2                 1           0    918                          800   
3                 0           0     88                          300   
4                 0           0    166                          600   
...             ...         ...    ...                          ...   
44117             0           0      0                          900   
44118             0           0     81                          800   
44119             0           0     27                         1500   
44120             0           1    236                         2500   
44121             0           0     13                         1500   

       pop_cuisines_count  cuisines_count  location_BTM  location_HSR  \
0                       3               3           0.0           0.0   
1                       2               3           0.0           0.0   
2                       2               3           0.0           0.0   
3                       2               2           0.0           0.0   
4                       1               2           0.0           0.0   
...                   ...             ...           ...           ...   
44117                   0               1           0.0           0.0   
44118                   3               4           0.0           0.0   
44119                   1               1           0.0           0.0   
44120                   0               1           0.0           0.0   
44121                   2               3           0.0           0.0   

       location_Indiranagar  location_JP Nagar  ...  \
0                       0.0                0.0  ...   
1                       0.0                0.0  ...   
2                       0.0                0.0  ...   
3                       0.0                0.0  ...   
4                       0.0                0.0  ...   
...                     ...                ...  ...   
44117                   0.0                0.0  ...   
44118                   0.0                0.0  ...   
44119                   0.0                0.0  ...   
44120                   0.0                0.0  ...   
44121                   0.0                0.0  ...   

       rest_type_first_Food Truck  rest_type_first_Kiosk  \
0                             0.0                    0.0   
1                             0.0                    0.0   
2                             0.0                    0.0   
3                             0.0                    0.0   
4                             0.0                    0.0   
...                           ...                    ...   
44117                         0.0                    0.0   
44118                         0.0                    0.0   
44119                         0.0                    0.0   
44120                         0.0                    0.0   
44121                         0.0                    0.0   

       rest_type_first_Lounge  rest_type_first_Mess  \
0                         0.0                   0.0   
1                         0.0                   0.0   
2                         0.0                   0.0   
3                         0.0                   0.0   
4                         0.0                   0.0   
...                       ...                   ...   
44117                     0.0                   0.0   
44118                     0.0                   0.0   
44119                     0.0                   0.0   
44120                     0.0                   0.0   
44121                     0.0                   0.0   

       rest_type_first_Microbrewery  rest_type_first_Pub  \
0                               0.0                  0.0   
1                               0.0                  0.0   
2                               0.0                  0

In [4]:
y

Rating
0         4.1
1         4.1
2         3.8
3         3.7
4         3.8
...       ...
44117     4.0
44118     2.5
44119     3.6
44120     4.3
44121     3.4

[44122 rows x 1 columns]

In [5]:
X.shape,y.shape

((44122, 56), (44122, 1))

In [6]:
'''Creates training and testing datasets for unbiased evaluation.'''
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [8]:
'''Trains a baseline linear regression model.'''
lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)
y_test,y_pred_lr

(       Rating
 5579      3.4
 26994     3.1
 29646     4.1
 10539     4.3
 29833     4.0
 ...       ...
 10226     4.1
 34407     3.8
 9057      3.1
 0         4.1
 18805     3.9
 
 [8825 rows x 1 columns],
 array([[3.5528395 ],
        [3.53538329],
        [3.85850439],
        ...,
        [3.5867447 ],
        [3.91731954],
        [4.24599774]]))

In [9]:
'''Evaluate Linear Regression
Evaluate base line model'''

rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))
r2_lr = r2_score(y_test, y_pred_lr)

rmse_lr, r2_lr


(np.float64(0.5129055767712619), 0.20349013694020635)

In [10]:
'''Train Ridge Regression
Trains a regularized linear model to reduce overfitting.'''

ridge = Ridge(alpha=1.0)
ridge.fit(X_train, y_train)

y_pred_ridge = ridge.predict(X_test)
y_test,y_pred_ridge

(       Rating
 5579      3.4
 26994     3.1
 29646     4.1
 10539     4.3
 29833     4.0
 ...       ...
 10226     4.1
 34407     3.8
 9057      3.1
 0         4.1
 18805     3.9
 
 [8825 rows x 1 columns],
 array([3.55287863, 3.53537971, 3.85856452, ..., 3.58669786, 3.91729346,
        4.24585168]))

In [11]:
''' Evaluates Ridge Regression performance.'''
rmse_ridge = np.sqrt(mean_squared_error(y_test, y_pred_ridge))
r2_ridge = r2_score(y_test, y_pred_ridge)

rmse_ridge, r2_ridge


(np.float64(0.5129028319674573), 0.20349866193019162)

In [12]:
'''Train Lasso Regression
Trains a model that performs implicit feature selection.'''
lasso = Lasso(alpha=0.001)
lasso.fit(X_train, y_train)

y_pred_lasso = lasso.predict(X_test)
y_test,y_pred_lasso

(       Rating
 5579      3.4
 26994     3.1
 29646     4.1
 10539     4.3
 29833     4.0
 ...       ...
 10226     4.1
 34407     3.8
 9057      3.1
 0         4.1
 18805     3.9
 
 [8825 rows x 1 columns],
 array([3.55750901, 3.52467357, 3.83825825, ..., 3.60193804, 3.91888622,
        4.24511531]))

In [14]:
'''Evaluates Lasso Regression performance.'''
rmse_lasso = np.sqrt(mean_squared_error(y_test, y_pred_lasso))
r2_lasso = r2_score(y_test, y_pred_lasso)

rmse_lasso, r2_lasso


(np.float64(0.5135789016870402), 0.2013975024068898)

In [15]:
'''Train Random Forest Regressor
Train Random Forest Regressor'''
rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
y_test,y_pred_rf

C:\Users\hp\anaconda3\envs\udemy_KNML\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


(       Rating
 5579      3.4
 26994     3.1
 29646     4.1
 10539     4.3
 29833     4.0
 ...       ...
 10226     4.1
 34407     3.8
 9057      3.1
 0         4.1
 18805     3.9
 
 [8825 rows x 1 columns],
 array([3.29167857, 3.206     , 4.101     , ..., 3.2095    , 4.098     ,
        3.9025    ]))

In [16]:
'''Evaluates Random Forest model performance.'''
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
r2_rf = r2_score(y_test, y_pred_rf)

rmse_rf, r2_rf


(np.float64(0.3207307728967198), 0.6885433720071445)

In [18]:
'''Compares all models to select the best performer.'''
results = pd.DataFrame({
    'Model': ['Linear', 'Ridge', 'Lasso', 'Random Forest'],
    'RMSE': [rmse_lr, rmse_ridge, rmse_lasso, rmse_rf],
    'R2': [r2_lr, r2_ridge, r2_lasso, r2_rf]
})

results.sort_values(by='RMSE')


Model      RMSE        R2
3  Random Forest  0.320731  0.688543
1          Ridge  0.512903  0.203499
0         Linear  0.512906  0.203490
2          Lasso  0.513579  0.201398

In [19]:
'''Chooses the best-performing model for further optimization.'''
best_model = rf
